### PR TITLE
added Tree traversal techniques inorder, preorder and postorder in c++ lang

### PR DESCRIPTION
**Pull request by abhstract**
PR for issue #101 
All traversals are based on recursion.

### CODE REVIEW

**Comment by abhstract** [comment]
Could you please tell me how long it would take to get hacktoberfest-accepted label??
Is the pr not elligible for that?
Thanks

**Comment by Anuja-19** [comment]
@abhstract 
I have already merged the PR. It is not necessary to put a label on it. Your review period must have started 9 days ago. Please check once.

**Comment by abhstract** [comment]
@Anuja-19 
Ok but one more thing that I noticed is I am unable to find my contribution in the folders. Actually being new to github I expected to see my it. Is this somehow related to hacktoberfest?? or have I done some mistake while deleting the file during pull request??
Thanks

**Comment by Anuja-19** [comment]
Do you mean the folder where you cloned the repository?

**Comment by Anuja-19** [comment]
I see that you have added an empty file to cpp folder. I have to revert the merge because its not valid. You can create a new pr with valid code. I will review and merge it.

**Comment by abhstract** [comment]
So basically what I am asking is in case of mutiple pr's The first pr would contain a single change whereas the second one would contain both the changes right?? because I found my second file having 3 changes do I deleted the previous change.

**Comment by Anuja-19** [comment]
When you create a PR and do the changes twice, it means you have one pr with multiple commits. So it is only one PR with multiple changes that you do not need to delete.
Now it just shows an empty file, please see if you can edit the file and add code in that empty file.

**Comment by abhstract** [comment]
@Anuja-19 Please review my pull request at the earliest.
Thanks.

**Pull request merged**
