### PR TITLE
Added Infix to postfix

### PR DESCRIPTION
**Pull request by Anuragkar234**
## Description of new pull request

**Program Added** -  3(Golang)
**Issue No.**- #102

## Checklist(self check):

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My Filename is in proper format
- [x] Proper commenting has been done

### CODE REVIEW

**Comment by Anuja-19** [comment]
@Anuragkar234 Thanks for your contribution. Do fill the form in the readme file, if you wish this snippet to be featured.
Greetings!

**Comment by Anuragkar234** [comment]
> @Anuragkar234 Thanks for your contribution. Do fill the form in the readme file, if you wish this snippet to be featured.
> Greetings!

can you hacktoberfest label to the repo, just a request though :)

**Comment by Anuragkar234** [comment]
> @Anuragkar234 Thanks for your contribution. Do fill the form in the readme file, if you wish this snippet to be featured.
> Greetings!

done!

**Comment by AnujaGD** [comment]
> > @Anuragkar234 Thanks for your contribution. Do fill the form in the readme file, if you wish this snippet to be featured.
> > Greetings!
> 
> can you hacktoberfest label to the repo, just a request though :)

Yes, Just read the new rules, Added the topic hacktoberfest to repo. Thank you !

**Comment by Anuja-19** [comment]
> > @Anuragkar234 Thanks for your contribution. Do fill the form in the readme file, if you wish this snippet to be featured.
> > Greetings!
> 
> done!

Just did. Thank you!

**Pull request merged**
