### PR TITLE
Add kadane's algo in js

### PR DESCRIPTION
**Pull request by syamilAbdillah**

### CODE REVIEW

**Comment by Anuja-19** [comment]
@syamilAbdillah Thanks for your contribution. Do fill the form in the readme file, if you wish this snippet to be featured.
Greetings!

**Comment by syamilAbdillah** [comment]
why this is not count in hacktoberfest ?

**Comment by Anuja-19** [comment]
It will count once reviewed and accepted.

**Comment by Anuja-19** [comment]
> @Anuja-19 why this is not count in hacktoberfest ?

It will count once reviewed and accepted.

**Comment by syamilAbdillah** [comment]
thanks a lot 😀, a few minutes ago i thought this repository is not participating in Hacktoberfest. but i am wrong.

sorry for my grammar. if you dont get it, just ignore it

**Comment by Anuja-19** [comment]
> thanks a lot 😀, a few minutes ago i thought this repository is not participating in Hacktoberfest. but i am wrong.
> 
> sorry for my grammar. if you dont get it, just ignore it

Hacktoberfest organizers just updated the rules, that's why it was showing that. I have updated the repository now :)

**Pull request merged**
